{% set name = "pdfcpu" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pdfcpu/pdfcpu/archive/v{{ version }}.tar.gz
  sha256: f92a3c0953acf4dc8d6e6c39fa89053f9e506ed1cbb1dcac13ea25ca03da8f03

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - pdfcpu help

about:
  home: https://github.com/pdfcpu/pdfcpu
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - license-files/
  summary: PDF processor written in Go
  dev_url: https://github.com/pdfcpu/pdfcpu

extra:
  recipe-maintainers:
    - danielnachun
