{% set name = "pdfcpu" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pdfcpu/pdfcpu/archive/v{{ version }}.tar.gz
  sha256: f43d55cf7a4c9a88a35c96c67891d3afc326b451059f516abe1837c51e2593dd

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - pdfcpu help

about:
  home: https://github.com/pdfcpu/pdfcpu
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - license-files/
  summary: PDF processor written in Go
  dev_url: https://github.com/pdfcpu/pdfcpu

extra:
  recipe-maintainers:
    - danielnachun
