schema_version: 1

context:
  version: "0.16.1"

package:
  name: pdfcpu
  version: ${{ version }}

source:
  url: https://github.com/pdfcpu/pdfcpu/archive/v${{ version }}.tar.gz
  sha256: bee48520012b0997b2de61114d3af6ea4d8a1d5fc8d98443de5ff231664155aa

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - pdfcpu help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - license-files/
  summary: PDF processor written in Go
  homepage: https://github.com/pdfcpu/pdfcpu
  repository: https://github.com/pdfcpu/pdfcpu

extra:
  recipe-maintainers:
    - danielnachun
