schema_version: 1

context:
  version: "0.14.0"

package:
  name: pdfcpu
  version: ${{ version }}

source:
  url: https://github.com/pdfcpu/pdfcpu/archive/v${{ version }}.tar.gz
  sha256: 9e824957d847af70585e9b5c94070e3b78377c876adadc0b90e37afcf706ba69

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - pdfcpu help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - license-files/
  summary: PDF processor written in Go
  homepage: https://github.com/pdfcpu/pdfcpu
  repository: https://github.com/pdfcpu/pdfcpu

extra:
  recipe-maintainers:
    - danielnachun
