schema_version: 1

context:
  version: "0.15.0"

package:
  name: pdfcpu
  version: ${{ version }}

source:
  url: https://github.com/pdfcpu/pdfcpu/archive/v${{ version }}.tar.gz
  sha256: 69924a7363ea19b4f3d4799ebf78bcabfec75a735c9569983a6e2834b5e8c6b3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - pdfcpu help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - license-files/
  summary: PDF processor written in Go
  homepage: https://github.com/pdfcpu/pdfcpu
  repository: https://github.com/pdfcpu/pdfcpu

extra:
  recipe-maintainers:
    - danielnachun
